[package]
name = "archi-bot"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "entity", "migration", "archi_client"]

[workspace.dependencies]
anyhow = "1.0"
dotenvy = "0.15"
poise = "0.6"
sea-orm = { version = "1.1", features = ["sqlx-sqlite", "runtime-tokio-rustls", "with-json"] }
serde = { version = "1.0", features = ["derive"]}
tokio = "1.44"

archi_client = {path = "archi_client" }
entity = { path = "entity" }
migration = {path = "migration" }

[dependencies]
anyhow.workspace = true
dotenvy.workspace = true
poise.workspace = true
sea-orm.workspace = true
tokio.workspace = true
entity.workspace = true
migration.workspace = true
archi_client.workspace = true
