[package]
name = "archi-bot"
version = "0.1.1"
edition = "2024"

[workspace]
members = ["crates/*", "."]

[workspace.dependencies]
anyhow = "1.0"
catppuccin = "2.5.1"
poise = "0.6"
sea-orm = { version = "1.1", features = ["sqlx-sqlite", "runtime-tokio-rustls", "with-json", "debug-print"] }
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0.140"
thiserror = "2.0"
tokio = "1.44"
tracing = "0.1"

# Custom Git dependencies
poise_error = { git = "https://github.com/pyrox0/poise-error", rev="9b79fd7aff48a621884bdcca87fd9d9efcc20918" }

# Local dependencies
archi_client = {path = "crates/archi_client" }
commands = { path = "crates/commands" }
entity = { path = "crates/entity" }
migration = { path = "crates/migration" }
utils = { path = "crates/utils" }


[dependencies]
# workspace crates.io dependencies
anyhow.workspace = true
catppuccin.workspace = true
poise.workspace = true
poise_error.workspace = true
sea-orm.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

# workspace local dependencies
archi_client.workspace = true
commands.workspace = true
entity.workspace = true
migration.workspace = true
utils.workspace = true

# non-workspace dependencies
tracing-subscriber = "0.3"
