words = [
    "aiofiles",
    "archi",
    "beautifulsoup",
    "bot's",
    "clearreg",
    "dotenv",
    "hikari",
    "miru",
    "orjson",
    "pprv",
    "pydantic",
    "rando",
    "setuptools",
    "sqlmodel",
    "tanjun",
    "uvloop",
    "venv",
    "wpd",
]
