//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "archi_player")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub team: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub slot: i32,
    pub name: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub room_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::archi_room::Entity",
        from = "Column::RoomId",
        to = "super::archi_room::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ArchiRoom,
}

impl Related<super::archi_room::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArchiRoom.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
