//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "discord_slot_link")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub slot_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub discord_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::archi_slot::Entity",
        from = "Column::SlotId",
        to = "super::archi_slot::Column::GlobalId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ArchiSlot,
    #[sea_orm(
        belongs_to = "super::discord_user::Entity",
        from = "Column::DiscordId",
        to = "super::discord_user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    DiscordUser,
}

impl Related<super::archi_slot::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArchiSlot.def()
    }
}

impl Related<super::discord_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscordUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
