//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "hint")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub receiving_player: i32,
    pub finding_player: i32,
    pub location: i64,
    pub item: i64,
    pub found: bool,
    pub entrance: String,
    pub item_flags: i32,
    pub room_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::archi_room::Entity",
        from = "Column::RoomId",
        to = "super::archi_room::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ArchiRoom,
}

impl Related<super::archi_room::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArchiRoom.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
