//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "discord_user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::discord_slot_link::Entity")]
    DiscordSlotLink,
}

impl Related<super::discord_slot_link::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscordSlotLink.def()
    }
}

impl Related<super::archi_slot::Entity> for Entity {
    fn to() -> RelationDef {
        super::discord_slot_link::Relation::ArchiSlot.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::discord_slot_link::Relation::DiscordUser.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
