//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "game_data_package")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub name: String,
    pub package_checksum: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::archi_slot::Entity")]
    ArchiSlot,
    #[sea_orm(has_many = "super::item::Entity")]
    Item,
    #[sea_orm(has_many = "super::location::Entity")]
    Location,
}

impl Related<super::archi_slot::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArchiSlot.def()
    }
}

impl Related<super::item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Item.def()
    }
}

impl Related<super::location::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Location.def()
    }
}

impl Related<super::item_group::Entity> for Entity {
    fn to() -> RelationDef {
        super::item::Relation::ItemGroup.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::item::Relation::GameDataPackage.def().rev())
    }
}

impl Related<super::location_group::Entity> for Entity {
    fn to() -> RelationDef {
        super::location::Relation::LocationGroup.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::location::Relation::GameDataPackage.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
