//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "rando_game")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub display_name: String,
    pub room_id: String,
    pub server_url: String,
    pub port: i16,
    pub bot_slot: String,
    pub game_channel: i64,
    pub tracker_url: String,
    pub room_url: String,
    pub spoil_traps: bool,
    pub active: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::archi_room::Entity",
        from = "Column::RoomId",
        to = "super::archi_room::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ArchiRoom,
}

impl Related<super::archi_room::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArchiRoom.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
